/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modul4Visual;

/**
 *
 * @author Acer
 */
public class SistemInformasiUnmul extends javax.swing.JFrame {

    /**
     * Creates new form SistemInformasiUnmul
     */
    public SistemInformasiUnmul() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAtas = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jBawah = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jKiri = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTengah = new javax.swing.JPanel();
        jkanan = new javax.swing.JPanel();
        hlmmuka = new javax.swing.JButton();
        hlmumum = new javax.swing.JButton();
        ungkuliah = new javax.swing.JButton();
        rgson = new javax.swing.JButton();
        wisuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jAtas.setBackground(new java.awt.Color(102, 102, 255));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Pictures\\unmuluf.png")); // NOI18N

        javax.swing.GroupLayout jAtasLayout = new javax.swing.GroupLayout(jAtas);
        jAtas.setLayout(jAtasLayout);
        jAtasLayout.setHorizontalGroup(
            jAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAtasLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jAtasLayout.setVerticalGroup(
            jAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAtasLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 95, Short.MAX_VALUE))
        );

        getContentPane().add(jAtas, java.awt.BorderLayout.CENTER);

        jBawah.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Pictures\\unmulll.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Sistem Informasi Akademik");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Biro Akademik dan Kemahasiswaan");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Universitas Mulawarman");

        javax.swing.GroupLayout jBawahLayout = new javax.swing.GroupLayout(jBawah);
        jBawah.setLayout(jBawahLayout);
        jBawahLayout.setHorizontalGroup(
            jBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBawahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(1109, Short.MAX_VALUE))
        );
        jBawahLayout.setVerticalGroup(
            jBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBawahLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jBawahLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addComponent(jLabel1))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jBawah, java.awt.BorderLayout.PAGE_START);

        jKiri.setBackground(new java.awt.Color(204, 51, 0));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MODUL PRAKTIKUM PEMROGRAM VISUAL");

        javax.swing.GroupLayout jKiriLayout = new javax.swing.GroupLayout(jKiri);
        jKiri.setLayout(jKiriLayout);
        jKiriLayout.setHorizontalGroup(
            jKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jKiriLayout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(jLabel5)
                .addContainerGap(753, Short.MAX_VALUE))
        );
        jKiriLayout.setVerticalGroup(
            jKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jKiriLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        getContentPane().add(jKiri, java.awt.BorderLayout.PAGE_END);

        jTengah.setBackground(new java.awt.Color(0, 204, 153));

        javax.swing.GroupLayout jTengahLayout = new javax.swing.GroupLayout(jTengah);
        jTengah.setLayout(jTengahLayout);
        jTengahLayout.setHorizontalGroup(
            jTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jTengahLayout.setVerticalGroup(
            jTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        getContentPane().add(jTengah, java.awt.BorderLayout.LINE_END);

        jkanan.setBackground(new java.awt.Color(102, 51, 255));
        jkanan.setLayout(new java.awt.GridLayout(0, 1));

        hlmmuka.setText("Halaman Muka");
        hlmmuka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hlmmukaActionPerformed(evt);
            }
        });
        jkanan.add(hlmmuka);

        hlmumum.setText("Halaman Umum");
        jkanan.add(hlmumum);

        ungkuliah.setText("Uang Tunggal Kuliah");
        jkanan.add(ungkuliah);

        rgson.setText("Registrasi Online");
        jkanan.add(rgson);

        wisuda.setText("Wisuda");
        jkanan.add(wisuda);

        getContentPane().add(jkanan, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hlmmukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hlmmukaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hlmmukaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemInformasiUnmul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemInformasiUnmul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemInformasiUnmul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemInformasiUnmul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemInformasiUnmul().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hlmmuka;
    private javax.swing.JButton hlmumum;
    private javax.swing.JPanel jAtas;
    private javax.swing.JPanel jBawah;
    private javax.swing.JPanel jKiri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jTengah;
    private javax.swing.JPanel jkanan;
    private javax.swing.JButton rgson;
    private javax.swing.JButton ungkuliah;
    private javax.swing.JButton wisuda;
    // End of variables declaration//GEN-END:variables
}
